services:

  postgres:
    image: postgres:15
    container_name: figma-back-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: figma_back_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  figma-back-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: figma-back-app
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=figma_back_db
      - SEED=true
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped
    command: npm run start:dev

volumes:
  pgdata:
